// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: cpu.proto

package ___cpu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StreamService_Stdout_FullMethodName = "/protobuf.StreamService/Stdout"
	StreamService_Stderr_FullMethodName = "/protobuf.StreamService/Stderr"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	Stdout(ctx context.Context, in *Request, opts ...grpc.CallOption) (StreamService_StdoutClient, error)
	Stderr(ctx context.Context, in *Request, opts ...grpc.CallOption) (StreamService_StderrClient, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) Stdout(ctx context.Context, in *Request, opts ...grpc.CallOption) (StreamService_StdoutClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_Stdout_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceStdoutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_StdoutClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type streamServiceStdoutClient struct {
	grpc.ClientStream
}

func (x *streamServiceStdoutClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) Stderr(ctx context.Context, in *Request, opts ...grpc.CallOption) (StreamService_StderrClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[1], StreamService_Stderr_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceStderrClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_StderrClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type streamServiceStderrClient struct {
	grpc.ClientStream
}

func (x *streamServiceStderrClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	Stdout(*Request, StreamService_StdoutServer) error
	Stderr(*Request, StreamService_StderrServer) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) Stdout(*Request, StreamService_StdoutServer) error {
	return status.Errorf(codes.Unimplemented, "method Stdout not implemented")
}
func (UnimplementedStreamServiceServer) Stderr(*Request, StreamService_StderrServer) error {
	return status.Errorf(codes.Unimplemented, "method Stderr not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_Stdout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).Stdout(m, &streamServiceStdoutServer{stream})
}

type StreamService_StdoutServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type streamServiceStdoutServer struct {
	grpc.ServerStream
}

func (x *streamServiceStdoutServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamService_Stderr_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).Stderr(m, &streamServiceStderrServer{stream})
}

type StreamService_StderrServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type streamServiceStderrServer struct {
	grpc.ServerStream
}

func (x *streamServiceStderrServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stdout",
			Handler:       _StreamService_Stdout_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stderr",
			Handler:       _StreamService_Stderr_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cpu.proto",
}
