[package]
name = "cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2-config = "^0.1.1"
ssh2 = "^0.9.1"
dirs = "4.0.0"
rpassword = "5.0.1"
