version: 2

templates:
  golang-template: &golang-template
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/u-root/cpu
    environment:
      - GOPATH: "/go"
      - CGO_ENABLED: 0

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    <<: *golang-template
    steps:
      - checkout
      - run: go env
      - run:
          name: Check vendored dependencies
          environment:
            - GO111MODULE: "on"
          command: |
            sudo apt install gox
            go mod tidy
            go mod verify
            git status
      - run: go build -mod=mod ./...
      - run: go test -mod=mod -timeout 15m -v ./...
      - run: |
          gox -os="linux" -arch="amd64 arm arm64 ppc64 ppc64le s390x mips mipsle mips64 mips64le" ./...
